// <auto-generated />
namespace ExplorePortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sitephotodatatypemodifiedtostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sitephotodatatypemodifiedtostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201801120951532_sitephoto datatype modified to string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
